version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    volumes:
      - app_data:/app/data # Mount a named volume for persistent data
    restart: unless-stopped

volumes:
  app_data: # Define the named volume
