version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    # environment:
      # NODE_ENV: production # Already set in Dockerfile
      # PORT: 3000 # If you need to override the port Next.js listens on inside the container
    restart: unless-stopped
    # You can add volumes for development if needed, e.g.:
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
